spring:
  application:
    name: chagok
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:3306/parkinghub
    username: valetparker
    password: valetparker

server:
  servlet:
    encoding:
      force: true

jwt:
  secret: LH9QZL8upsPBfuDY+Dkb1kT9DZIIUSuA2u4O6Lfi3mkEfeWtETpVTcR/8SMZdJWn/xNTuCQBE6rBvDXgnVmscQ==
  expiration: 1800000
  refresh-expiration: 604800000

kakaopay:
  secretKey:
  cid: pay