spring:
  application:
    name: chagok
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:3306/parkinghub
    username: valetparker
    password: valetparker
kakaopay:
  secretKey:
  cid:
profile:
  active: pay

server:
  servlet:
    encoding:
      force: true
